version: "3.11"

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: summarizer
    ports:
      - "${PORT}:8000"
    command: "uvicorn backend.app.main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../backend/:/app/